=== badukboy/BCIT/bcit-work/php/xml_processing/data/populations_v2.dtd
<!--
    Document   : populations_v2.dtd
    Created on : February 2, 2013
    Author     : Kevin Csapko
    Description: British Columbia Regional District and Municipal Population 
                 Estimates, version 2 DTD
-->

<!-- 
    A district can have any amount of records, and the district name is
    required.
 -->
<!ELEMENT district (record)+>
<!ATTLIST district name CDATA #REQUIRED>

<!--
    Each record consists of a region, a year, and a population.
-->
<!ELEMENT record (region,year,population)>

<!--
    Each region must contain parsed character data (the region name), as well as
    an attribute for the SGC (standard geographical classification), and the
    region type (city, village, etc.)
-->
<!ELEMENT region (#PCDATA)>
<!ATTLIST region sgc CDATA #REQUIRED>
<!ATTLIST region type CDATA #REQUIRED>

<!--
    The year and population elements simply contain parsed character data that
    holds the year and population of the region respectively.
-->
<!ELEMENT year (#PCDATA)>
<!ELEMENT population (#PCDATA)>

=== badukboy/BCIT/bcit-work/php/xml_processing/data/populations_v2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE district SYSTEM "populations_v2.dtd">

<!--
    Document   : populations_v2.xml
    Created on : January 30, 2013
    Author     : Kevin Csapko
    Description: British Columbia Regional District and Municipal Population 
                 Estimates, version 2 based on feedback from Lab 3.
-->

<district name="Fraser Valley">
    <record>
        <region sgc="9052" type="C">Abbotsford</region>
        <year>2006</year>
        <population>129345</population>
    </record>
    <record>
        <region sgc="9052" type="C">Abbotsford</region>
        <year>2007</year>
        <population>131243</population>
    </record>
    <record>
        <region sgc="9052" type="C">Abbotsford</region>
        <year>2008</year>
        <population>133547</population>
    </record>
    <record>
        <region sgc="9052" type="C">Abbotsford</region>
        <year>2009</year>
        <population>136021</population>
    </record>
    <record>
        <region sgc="9052" type="C">Abbotsford</region>
        <year>2010</year>
        <population>138124</population>
    </record>
    <record>
        <region sgc="9052" type="C">Abbotsford</region>
        <year>2011</year>
        <population>139430</population>
    </record>
    <record>
        <region sgc="9052" type="C">Abbotsford</region>
        <year>2012</year>
        <population>140235</population>
    </record>
    <record>
        <region sgc="9020" type="C">Chilliwack</region>
        <year>2006</year>
        <population>71298</population>
    </record>
    <record>
        <region sgc="9020" type="C">Chilliwack</region>
        <year>2007</year>
        <population>73296</population>
    </record>
    <record>
        <region sgc="9020" type="C">Chilliwack</region>
        <year>2008</year>
        <population>74943</population>
    </record>
    <record>
        <region sgc="9020" type="C">Chilliwack</region>
        <year>2009</year>
        <population>76193</population>
    </record>
    <record>
        <region sgc="9020" type="C">Chilliwack</region>
        <year>2010</year>
        <population>77944</population>
    </record>
    <record>
        <region sgc="9020" type="C">Chilliwack</region>
        <year>2011</year>
        <population>78947</population>
    </record>
    <record>
        <region sgc="9020" type="C">Chilliwack</region>
        <year>2012</year>
        <population>79617</population>
    </record>
    <record>
        <region sgc="9027" type="VL">Harrison Hot Springs</region>
        <year>2006</year>
        <population>1578</population>
    </record>
    <record>
        <region sgc="9027" type="VL">Harrison Hot Springs</region>
        <year>2007</year>
        <population>1584</population>
    </record>
    <record>
        <region sgc="9027" type="VL">Harrison Hot Springs</region>
        <year>2008</year>
        <population>1597</population>
    </record>
    <record>
        <region sgc="9027" type="VL">Harrison Hot Springs</region>
        <year>2009</year>
        <population>1596</population>
    </record>
    <record>
        <region sgc="9027" type="VL">Harrison Hot Springs</region>
        <year>2010</year>
        <population>1597</population>
    </record>
    <record>
        <region sgc="9027" type="VL">Harrison Hot Springs</region>
        <year>2011</year>
        <population>1598</population>
    </record>
    <record>
        <region sgc="9027" type="VL">Harrison Hot Springs</region>
        <year>2012</year>
        <population>1606</population>
    </record>
    <record>
        <region sgc="9009" type="DM">Hope</region>
        <year>2006</year>
        <population>6243</population>
    </record>
    <record>
        <region sgc="9009" type="DM">Hope</region>
        <year>2007</year>
        <population>6161</population>
    </record>
    <record>
        <region sgc="9009" type="DM">Hope</region>
        <year>2008</year>
        <population>6203</population>
    </record>
    <record>
        <region sgc="9009" type="DM">Hope</region>
        <year>2009</year>
        <population>6276</population>
    </record>
    <record>
        <region sgc="9009" type="DM">Hope</region>
        <year>2010</year>
        <population>6319</population>
    </record>
    <record>
        <region sgc="9009" type="DM">Hope</region>
        <year>2011</year>
        <population>6204</population>
    </record>
    <record>
        <region sgc="9009" type="DM">Hope</region>
        <year>2012</year>
        <population>6136</population>
    </record>
    <record>
        <region sgc="9032" type="DM">Kent</region>
        <year>2006</year>
        <population>5318</population>
    </record>
    <record>
        <region sgc="9032" type="DM">Kent</region>
        <year>2007</year>
        <population>5341</population>
    </record>
    <record>
        <region sgc="9032" type="DM">Kent</region>
        <year>2008</year>
        <population>5461</population>
    </record>
    <record>
        <region sgc="9032" type="DM">Kent</region>
        <year>2009</year>
        <population>5521</population>
    </record>
    <record>
        <region sgc="9032" type="DM">Kent</region>
        <year>2010</year>
        <population>5577</population>
    </record>
    <record>
        <region sgc="9032" type="DM">Kent</region>
        <year>2011</year>
        <population>5539</population>
    </record>
    <record>
        <region sgc="9032" type="DM">Kent</region>
        <year>2012</year>
        <population>5564</population>
    </record>
    <record>
        <region sgc="9056" type="DM">Mission</region>
        <year>2006</year>
        <population>35741</population>
    </record>
    <record>
        <region sgc="9056" type="DM">Mission</region>
        <year>2007</year>
        <population>36281</population>
    </record>
    <record>
        <region sgc="9056" type="DM">Mission</region>
        <year>2008</year>
        <population>36758</population>
    </record>
    <record>
        <region sgc="9056" type="DM">Mission</region>
        <year>2009</year>
        <population>37210</population>
    </record>
    <record>
        <region sgc="9056" type="DM">Mission</region>
        <year>2010</year>
        <population>37559</population>
    </record>
    <record>
        <region sgc="9056" type="DM">Mission</region>
        <year>2011</year>
        <population>37395</population>
    </record>
    <record>
        <region sgc="9056" type="DM">Mission</region>
        <year>2012</year>
        <population>37614</population>
    </record>
    <record>
        <region sgc="9999" type="RDR">Unincorporated Areas</region>
        <year>2006</year>
        <population>17204</population>
    </record>
    <record>
        <region sgc="9999" type="RDR">Unincorporated Areas</region>
        <year>2007</year>
        <population>17365</population>
    </record>
    <record>
        <region sgc="9999" type="RDR">Unincorporated Areas</region>
        <year>2008</year>
        <population>17807</population>
    </record>
    <record>
        <region sgc="9999" type="RDR">Unincorporated Areas</region>
        <year>2009</year>
        <population>17714</population>
    </record>
    <record>
        <region sgc="9999" type="RDR">Unincorporated Areas</region>
        <year>2010</year>
        <population>17761</population>
    </record>
    <record>
        <region sgc="9999" type="RDR">Unincorporated Areas</region>
        <year>2011</year>
        <population>18046</population>
    </record>
    <record>
        <region sgc="9999" type="RDR">Unincorporated Areas</region>
        <year>2012</year>
        <population>18047</population>
    </record>
</district>
